In [3]:
import pandas as pd 

df = pd.read_csv("sklearn_data.csv")

df

       tag                                               text
0       h1                                       User Guide #
1        p                                 Section Navigation
2        p                                           previous
3        p                            Installing scikit-learn
4        p                                               next
...    ...                                                ...
12433  pre  >>> from sklearn.datasets import load_iris >>>...
12434  pre  >>> from sklearn.metrics import make_scorer , ...
12435   h1                                 sklearn.ensemble #
12436    p  Ensemble-based methods for classification, reg...
12437    p  User guide. See the Ensembles: Gradient boosti...

[12438 rows x 2 columns]

In [4]:
df.drop(columns=['tag'],inplace=True)
df.set_index("text")

Empty DataFrame
Columns: []
Index: [User Guide #, Section Navigation, previous, Installing scikit-learn, next, 1. Supervised learning, scikit-learn is financially supported by Probabl and other
        institutions., Enterprise-grade solutions and services, © Copyright 2007 - 2026, scikit-learn developers (BSD License)., 1. Supervised learning #, User Guide, 1.1. Linear Models, 1.1. Linear Models #, 1.1.1. Ordinary Least Squares #, 1.1.2. Ridge regression and classification #, 1.1.3. Lasso #, 1.1.4. Multi-task Lasso #, 1.1.5. Elastic-Net #, 1.1.6. Multi-task Elastic-Net #, 1.1.7. Least Angle Regression #, 1.1.8. LARS Lasso #, 1.1.9. Orthogonal Matching Pursuit (OMP) #, 1.1.10. Bayesian Regression #, 1.1.11. Logistic regression #, 1.1.12. Generalized Linear Models #, 1.1.13. Stochastic Gradient Descent - SGD #, 1.1.14. Robustness regression: outliers and modeling errors #, 1.1.15. Quantile Regression #, 1.1.16. Polynomial regression: extending linear models with basis functions #, 1.1.1.1. Non-Negative Least Squares #, 1.1.1.2. Ordinary Least Squares Complexity #, 1.1.2.1. Regression #, 1.1.2.2. Classification #, 1.1.2.3. Ridge Complexity #, 1.1.2.4. Setting the regularization parameter: leave-one-out Cross-Validation #, 1.1.3.1. Coordinate Descent with Gap Safe Screening Rules #, 1.1.3.2. Setting regularization parameter #, 1.1.10.1. Bayesian Ridge Regression #, 1.1.10.2. Automatic Relevance Determination - ARD #, 1.1.11.1. Binary Case #, 1.1.11.2. Multinomial Case #, 1.1.11.3. Solvers #, 1.1.12.1. Usage #, 1.1.13.1. Perceptron #, 1.1.13.2. Passive Aggressive Algorithms #, 1.1.14.1. Different scenario and useful concepts #, 1.1.14.2. RANSAC: RANdom SAmple Consensus #, 1.1.14.3. Theil-Sen estimator: generalized-median-based estimator #, 1.1.14.4. Huber Regression #, The following are a set of methods intended for regression in which
the target value is expected to be a linear combination of the features.
In mathematical notation, the predicted value \(\hat{y}\) can be
written as:, Across the module, we designate the vector \(w = (w_1,
..., w_p)\) as coef_ and \(w_0\) as intercept_ ., To perform classification with generalized linear models, see Logistic regression ., LinearRegression fits a linear model with coefficients \(w = (w_1, ..., w_p)\) to minimize the residual sum
of squares between the observed targets in the dataset, and the
targets predicted by the linear approximation. Mathematically it
solves a problem of the form:, LinearRegression takes in its fit method arguments X , y , sample_weight and stores the coefficients \(w\) of the linear model in its coef_ and intercept_ attributes:, The coefficient estimates for Ordinary Least Squares rely on the
independence of the features. When features are correlated and some
columns of the design matrix \(X\) have an approximately linear
dependence, the design matrix becomes close to singular
and as a result, the least-squares estimate becomes highly sensitive
to random errors in the observed target, producing a large
variance. This situation of multicollinearity can arise, for
example, when data are collected without an experimental design., Examples, Ordinary Least Squares and Ridge Regression, It is possible to constrain all the coefficients to be non-negative, which may
be useful when they represent some physical or naturally non-negative
quantities (e.g., frequency counts or prices of goods). LinearRegression accepts a boolean positive parameter: when set to True Non-Negative Least Squares are then applied., Non-negative least squares, The least squares solution is computed using the singular value
decomposition of \(X\) . If \(X\) is a matrix of shape (n_samples, n_features) this method has a cost of \(O(n_{\text{samples}} n_{\text{features}}^2)\) , assuming that \(n_{\text{samples}} \geq n_{\text{features}}\) ., Ridge regression addresses some of the problems of Ordinary Least Squares by imposing a penalty on the size of the
coefficients. The ridge coefficients minimize a penalized residual sum
of squares:, The complexity parameter \(\alpha \geq 0\) controls the amount
of shrinkage: the larger the value of \(\alpha\) , the greater the amount
of shrinkage and thus the coefficients become more robust to collinearity., As with other linear models, Ridge will take in its fit method
arrays X , y and will store the coefficients \(w\) of the linear model in
its coef_ member:, Note that the class Ridge allows for the user to specify that the
solver be automatically chosen by setting solver="auto" . When this option
is specified, Ridge will choose between the "lbfgs" , "cholesky" ,
and "sparse_cg" solvers. Ridge will begin checking the conditions
shown in the following table from top to bottom. If the condition is true,
the corresponding solver is chosen., Solver, Condition, ‘lbfgs’, The positive=True option is specified., ‘cholesky’, The input array X is not sparse., ‘sparse_cg’, None of the above conditions are fulfilled., Plot Ridge coefficients as a function of the regularization, Common pitfalls in the interpretation of coefficients of linear models, Ridge coefficients as a function of the L2 Regularization, The Ridge regressor has a classifier variant: RidgeClassifier . This classifier first converts binary targets to {-1, 1} and then treats the problem as a regression task, optimizing the
same objective as above. The predicted class corresponds to the sign of the
regressor’s prediction. For multiclass classification, the problem is
treated as multi-output regression, and the predicted class corresponds to
the output with the highest value., It might seem questionable to use a (penalized) Least Squares loss to fit a
classification model instead of the more traditional logistic or hinge
losses. However, in practice, all those models can lead to similar
cross-validation scores in terms of accuracy or precision/recall, while the
penalized least squares loss used by the RidgeClassifier allows for
a very different choice of the numerical solvers with distinct computational
performance profiles., The RidgeClassifier can be significantly faster than e.g. LogisticRegression with a high number of classes because it can
compute the projection matrix \((X^T X)^{-1} X^T\) only once., This classifier is sometimes referred to as a Least Squares Support Vector
Machine with
a linear kernel., Classification of text documents using sparse features, This method has the same order of complexity as Ordinary Least Squares ., RidgeCV and RidgeClassifierCV implement ridge
regression/classification with built-in cross-validation of the alpha parameter.
They work in the same way as GridSearchCV except
that it defaults to efficient Leave-One-Out cross-validation .
When using the default cross-validation , alpha cannot be 0 due to the
formulation used to calculate Leave-One-Out error. See [RL2007] for details., Usage example:, Specifying the value of the cv attribute will trigger the use of
cross-validation with GridSearchCV , for
example cv=10 for 10-fold cross-validation, rather than Leave-One-Out
Cross-Validation., “Notes on Regularized Least Squares”, Rifkin & Lippert ( technical report , course slides )., The Lasso is a linear model that estimates sparse coefficients, i.e., it is
able to set coefficients exactly to zero.
It is useful in some contexts due to its tendency to prefer solutions
with fewer non-zero coefficients, effectively reducing the number of
features upon which the given solution is dependent. For this reason,
Lasso and its variants are fundamental to the field of compressed sensing.
Under certain conditions, it can recover the exact set of non-zero coefficients (see Compressive sensing: tomography reconstruction with L1 prior (Lasso) )., Mathematically, it consists of a linear model with an added regularization term.
The objective function to minimize is:, The lasso estimate thus solves the least-squares with added penalty \(\alpha ||w||_1\) , where \(\alpha\) is a constant and \(||w||_1\) is the \(\ell_1\) -norm of the coefficient vector., The implementation in the class Lasso uses coordinate descent as
the algorithm to fit the coefficients. See Least Angle Regression for another implementation:, The function lasso_path is useful for lower-level tasks, as it
computes the coefficients along the full path of possible values., L1-based models for Sparse Signals, Compressive sensing: tomography reconstruction with L1 prior (Lasso), Lasso model selection: AIC-BIC / cross-validation, Note, Feature selection with Lasso, As the Lasso regression yields sparse models, it can
thus be used to perform feature selection, as detailed in L1-based feature selection ., The following references explain the origin of the Lasso as well as properties
of the Lasso problem and the duality gap computation used for convergence control., Robert Tibshirani. (1996) Regression Shrinkage and Selection Via the Lasso.
J. R. Stat. Soc. Ser. B Stat. Methodol., 58(1):267-288, “An Interior-Point Method for Large-Scale L1-Regularized Least Squares,”
S. J. Kim, K. Koh, M. Lustig, S. Boyd and D. Gorinevsky,
in IEEE Journal of Selected Topics in Signal Processing, 2007
( Paper ), Coordinate descent (CD) is a strategy to solve a minimization problem that considers a
single feature \(j\) at a time. This way, the optimization problem is reduced to a
1-dimensional problem which is easier to solve:, ...]

[12438 rows x 0 columns]

In [5]:
def chunking(data: pd.DataFrame, chunk_size=500):
    chunks = []

    for i in range(0, len(data), chunk_size):
        chunks.append(data.iloc[i:i + chunk_size])

    return chunks

In [6]:
chunking(df)

[                                                  text
 0                                         User Guide #
 1                                   Section Navigation
 2                                             previous
 3                              Installing scikit-learn
 4                                                 next
 ..                                                 ...
 495  Computing Euclidean distances in this d-dimens...
 496  We can reduce the dimension even more, to a ch...
 497  Shrinkage is a form of regularization used to ...
 498  The shrinkage parameter can also be manually s...
 499  The shrunk Ledoit and Wolf estimator of covari...

 [500 rows x 1 columns],
                                                   text
 500  The covariance estimator can be chosen using t...
 501  Normal, Ledoit-Wolf and OAS Linear Discriminan...
 502  Using LDA and QDA requires computing the log-p...
 503  The ‘svd’ solver is the default solver used fo...
 504  The 'lsqr' solver is an efficient algorithm th...
 ..                                                 ...
 995  The RationalQuadratic kernel can be seen as a ...
 996  The prior and posterior of a GP resulting from...
 997  The ExpSineSquared kernel allows modeling peri...
 998  The prior and posterior of a GP resulting from...
 999  The DotProduct kernel is non-stationary and ca...

 [500 rows x 1 columns],
                                                    text
 1000  The DotProduct kernel is commonly combined wit...
 1001  Carl E. Rasmussen and Christopher K.I. William...
 1002  David Duvenaud, “The Kernel Cookbook: Advice o...
 1003                           1.8. Cross decomposition
 1004  >>> from sklearn.gaussian_process.kernels impo...
 ...                                                 ...
 1495  The final_estimator will use the predictions o...
 1496  To train the estimators and final_estimator , ...
 1497  During training, the estimators are fitted on ...
 1498  For StackingClassifier , note that the output ...
 1499  A StackingRegressor and StackingClassifier can...

 [500 rows x 1 columns],
                                                    text
 1500  Note that it is also possible to get the outpu...
 1501  In practice, a stacking predictor predicts as ...
 1502  For StackingClassifier , when using stack_meth...
 1503  Multiple stacking layers can be achieved by as...
 1504                  Combine predictors using stacking
 ...                                                 ...
 1995  Variational inference techniques for the Diric...
 1996                             2.2. Manifold learning
 1997                           2.2. Manifold learning #
 1998                              2.2.1. Introduction #
 1999                                    2.2.2. Isomap #

 [500 rows x 1 columns],
                                                    text
 2000                  2.2.3. Locally Linear Embedding #
 2001         2.2.4. Modified Locally Linear Embedding #
 2002                      2.2.5. Hessian Eigenmapping #
 2003                        2.2.6. Spectral Embedding #
 2004             2.2.7. Local Tangent Space Alignment #
 ...                                                 ...
 2495  Caliński, T., & Harabasz, J. (1974). “A Dendri...
 2496  If the ground truth labels are not known, the ...
 2497  This index signifies the average ‘similarity’ ...
 2498  Zero is the lowest possible score. Values clos...
 2499  In normal usage, the Davies-Bouldin index is a...

 [500 rows x 1 columns],
                                                    text
 2500  The computation of Davies-Bouldin is simpler t...
 2501  The index is solely based on quantities and fe...
 2502  The Davies-Bouldin index is generally higher f...
 2503  The usage of centroid distance limits the dist...
 2504  The index is defined as the average similarity...
 ...                                                 ...
 2995  The model makes assumptions regarding the dist...
 2996  The RBM tries to maximize the likelihood of th...
 2997  The method gained popularity for initializing ...
 2998  Restricted Boltzmann Machine features for digi...
 2999  The graphical model of an RBM is a fully-conne...

 [500 rows x 1 columns],
                                                    text
 3000  The nodes are random variables whose states de...
 3001  The energy function measures the quality of a ...
 3002  In the formula above, \(\mathbf{b}\) and \(\ma...
 3003  The word restricted refers to the bipartite st...
 3004  The bipartite structure allows for the use of ...
 ...                                                 ...
 3495                                     Classification
 3496                                               mean
 3497                                      Brier score 1
 3498                                        multi-class
 3499                                      predict_proba

 [500 rows x 1 columns],
                                                    text
 3500                                           log loss
 3501                                               mode
 3502                                    zero-one loss 2
 3503                              predict , categorical
 3504                                         Regression
 ...                                                 ...
 3995  DCG orders the true targets (e.g. relevance of...
 3996  Compared with the ranking loss, NDCG can take ...
 3997  For one sample, given the vector of continuous...
 3998  and the NDCG score is the DCG score divided by...
 3999     Wikipedia entry for Discounted Cumulative Gain

 [500 rows x 1 columns],
                                                    text
 4000  Jarvelin, K., & Kekalainen, J. (2002).\nCumula...
 4001  Wang, Y., Wang, L., Li, Y., He, D., Chen, W., ...
 4002  McSherry, F., & Najork, M. (2008, March). Comp...
 4003  The sklearn.metrics module implements several ...
 4004  These functions have a multioutput keyword arg...
 ...                                                 ...
 4495                                   8.1.1.1. Usage #
 4496  8.1.1.2. Caching transformers: avoid repeated ...
 4497                                   8.1.3.1. Usage #
 4498  To build a composite estimator, transformers a...
 4499  Pipeline can be used to chain multiple estimat...

 [500 rows x 1 columns],
                                                    text
 4500  You only have to call fit and predict once on ...
 4501  You can grid search over parameters of all est...
 4502  Pipelines help avoid leaking statistics from y...
 4503  All estimators in a pipeline, except the last ...
 4504  Calling fit on the pipeline is the same as cal...
 ...                                                 ...
 4995  >>> quantile_transformer = preprocessing . Qua...
 4996  >>> X = [[ 1. , - 1. , 2. ], ... [ 2. , 0. , 0...
 4997  >>> normalizer = preprocessing . Normalizer ()...
 4998  >>> normalizer . transform ( X ) array([[ 0.40...
 4999  >>> enc = preprocessing . OrdinalEncoder () >>...

 [500 rows x 1 columns],
                                                    text
 5000  >>> enc = preprocessing . OrdinalEncoder () >>...
 5001  >>> enc = preprocessing . OrdinalEncoder ( enc...
 5002  >>> from sklearn.pipeline import Pipeline >>> ...
 5003  >>> enc = preprocessing . OneHotEncoder () >>>...
 5004  >>> enc . categories_ [array(['female', 'male'...
 ...                                                 ...
 5495    30 numeric, predictive attributes and the class
 5496  radius (mean of distances from center to point...
 5497  texture (standard deviation of gray-scale values)
 5498                                          perimeter
 5499                                               area

 [500 rows x 1 columns],
                                                    text
 5500     smoothness (local variation in radius lengths)
 5501             compactness (perimeter^2 / area - 1.0)
 5502  concavity (severity of concave portions of the...
 5503  concave points (number of concave portions of ...
 5504                                           symmetry
 ...                                                 ...
 5995   scikit-learn developer performance documentation
 5996          Scipy sparse matrix formats documentation
 5997  10.3. Parallelism, resource management, and co...
 5998  >>> import sklearn >>> with sklearn . config_c...
 5999  def sparsity_ratio ( X ): return 1.0 - np . co...

 [500 rows x 1 columns],
                                                    text
 6000  python - c "import sklearn; sklearn.show_versi...
 6001  >>> import sklearn >>> with sklearn . config_c...
 6002  clf = SGDRegressor ( penalty = 'elasticnet' , ...
 6003  10.3. Parallelism, resource management, and co...
 6004                              10.3.1. Parallelism #
 ...                                                 ...
 6495                                     Target Types #
 6496                                          Methods #
 6497                                       Parameters #
 6498                                       Attributes #
 6499                       Data and sample properties #

 [500 rows x 1 columns],
                                                    text
 6500  This glossary hopes to definitively represent ...
 6501  We begin by listing general concepts (and any ...
 6502  One-dimensional array. A NumPy array whose .sh...
 6503  Two-dimensional array. A NumPy array whose .sh...
 6504  Refers to both the specific interfaces for est...
 ...                                                 ...
 6995  The relative tolerance is automatically inferr...
 6996  When comparing arrays of zero-elements, please...
 6997  For more information, please refer to the docs...
 6998     estimator = estimator . fit ( data , targets )
 6999               estimator = estimator . fit ( data )

 [500 rows x 1 columns],
                                                    text
 7000          prediction = predictor . predict ( data )
 7001   probability = predictor . predict_proba ( data )
 7002        new_data = transformer . transform ( data )
 7003    new_data = transformer . fit_transform ( data )
 7004                     score = model . score ( data )
 ...                                                 ...
 7495              Least Angle Regression model aka LAR.
 7496                                             LarsCV
 7497                                              Lasso
 7498  Linear Model trained with L1 prior as regulari...
 7499                                            LassoCV

 [500 rows x 1 columns],
                                                    text
 7500                                          LassoLars
 7501  Lasso model fit with Least Angle Regression ak...
 7502                                        LassoLarsCV
 7503                                        LassoLarsIC
 7504                          OrthogonalMatchingPursuit
 ...                                                 ...
 7995        Make arrays indexable for cross-validation.
 7996                                     murmurhash3_32
 7997      Compute the 32bit murmurhash3 of key at seed.
 7998                                           resample
 7999  Resample arrays or sparse matrices in a consis...

 [500 rows x 1 columns],
                                                    text
 8000                                          safe_mask
 8001           Return a mask which is safe to use on X.
 8002                                           safe_sqr
 8003  Element wise squaring of array-likes and spars...
 8004                                            shuffle
 ...                                                 ...
 8495  legacy: a set of checks which gradually will b...
 8496                       Estimator instance to check.
 8497  Whether to include legacy checks. Over time we...
 8498                              Added in version 1.6.
 8499                          A dictionary of the form:

 [500 rows x 1 columns],
                                                    text
 8500  Where "check_name" is the name of the check, a...
 8501  This parameter controls what happens when a ch...
 8502  “warn”: A SkipTestWarning is logged\nand runni...
 8503  None: No warning is logged and running tests c...
 8504  This parameter controls what happens when a ch...
 ...                                                 ...
 8995    Added in version 0.20: Added ‘adaptive’ option.
 8996  Added in version 1.8: Added options ‘pa1’ and ...
 8997  The initial learning rate for the ‘constant’, ...
 8998  For PA-1 ( learning_rate=pa1 ) and PA-II ( pa2...
 8999              For PA-I it is the maximum step size.

 [500 rows x 1 columns],
                                                    text
 9000  For PA-II it regularizes the step size (the sm...
 9001  As a general rule-of-thumb for PA, eta0 should...
 9002  The exponent for inverse scaling learning rate...
 9003  Deprecated since version 1.8: Negative values ...
 9004  Whether to use early stopping to terminate tra...
 ...                                                 ...
 9495  >>> import numpy as np >>> from sklearn.prepro...
 9496  >>> # A high `smooth` parameter puts more weig...
 9497  >>> # On the other hand, a low `smooth` parame...
 9498                                StackingRegressor #
 9499  Stacked generalization consists in stacking th...

 [500 rows x 1 columns],
                                                    text
 9500  A regressor which will be used to combine the ...
 9501  The regressor fit on the output of estimators_...
 9502                         Returns a fitted instance.
 9503  Fit the estimators and return the predictions ...
 9504  Return coefficient of determination on test data.
 ...                                                 ...
 9995          Density Estimation for a Gaussian mixture
 9996                         GMM Initialization Methods
 9997                                    GMM covariances
 9998                  Gaussian Mixture Model Ellipsoids
 9999                  Gaussian Mixture Model Sine Curve

 [500 rows x 1 columns],
                                                     text
 10000  Examples concerning the sklearn.gaussian_proce...
 10001  Gaussian process classification (GPC) on iris ...
 10002     Gaussian processes on discrete data structures
 10003  Illustration of Gaussian process classificatio...
 10004  Illustration of prior and posterior Gaussian p...
 ...                                                  ...
 10495  The perplexity is related to the number of nea...
 10496  Controls how tight natural clusters in the ori...
 10497  The learning rate for t-SNE is usually in the ...
 10498  Changed in version 1.2: The default value chan...
 10499  Maximum number of iterations for the optimizat...

 [500 rows x 1 columns],
                                                     text
 10500  Changed in version 1.5: Parameter name changed...
 10501  Maximum number of iterations without progress ...
 10502  Added in version 0.17: parameter n_iter_withou...
 10503  If the gradient norm is below this threshold, ...
 10504  The metric to use when calculating distance be...
 ...                                                  ...
 10995  When an estimator consumes a metadata which it...
 10996  At the end we disable the configuration flag f...
 10997  As seen above, information is communicated bet...
 10998         your estimator inherits from BaseEstimator
 10999  the parameters consumed by your estimator’s me...

 [500 rows x 1 columns],
                                                     text
 11000  your estimator does not route any metadata to ...
 11001  Total running time of the script: (0 minutes 0...
 11002  Download Jupyter notebook: plot_metadata_routi...
 11003  Download Python source code: plot_metadata_rou...
 11004         Download zipped: plot_metadata_routing.zip
 ...                                                  ...
 11495  Whether to use a precomputed Gram matrix to sp...
 11496  If True , X will be copied; otherwise, it may ...
 11497  If positive, restrict regression coefficients ...
 11498             Independent term in decision function.
 11499  Mean square error for the test set on each fol...

 [500 rows x 1 columns],
                                                     text
 11500               The grid of alphas used for fitting.
 11501  The dual gap at the end of the optimization fo...
 11502  The Lasso is a linear model that estimates spa...
 11503    Cross-validated Lasso using the LARS algorithm.
 11504  LassoCV leads to different results than a hype...
 ...                                                  ...
 11995  These hooks are only called once, respectively...
 11996              on_fit_task_begin and on_fit_task_end
 11997  These hooks are called at the beginning and en...
 11998  In concrete implementations of callbacks, only...
 11999  These arguments must be defined as keyword onl...

 [500 rows x 1 columns],
                                                     text
 12000  Even if requested, the optional arguments migh...
 12001  The on_fit_task_end hook returns a boolean, wh...
 12002  All the hooks receive, as mandatory arguments,...
 12003  The estimator instance received by the hooks, ...
 12004  Auto-propagated callbacks, i.e. callbacks that...
 ...                                                  ...
 12433  >>> from sklearn.datasets import load_iris >>>...
 12434  >>> from sklearn.metrics import make_scorer , ...
 12435                                 sklearn.ensemble #
 12436  Ensemble-based methods for classification, reg...
 12437  User guide. See the Ensembles: Gradient boosti...

 [438 rows x 1 columns]]

john

In [7]:
chunks = chunking(df)

In [8]:
chunk_texts = []

for chunk in chunks:
    text = " ".join(chunk["text"].astype(str).tolist())
    chunk_texts.append(text)

In [33]:
from langchain_core.documents import Document

docs = [Document(page_content=text) for text in chunk_texts]

In [34]:
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

In [35]:
embeddings = HuggingFaceEmbeddings(model="sentence-transformers/all-MiniLM-L6-v2")

vdb = Chroma.from_documents(
    documents=docs,
    embedding=embeddings,
    persist_directory="route"
)

In [36]:
retriever = vdb.as_retriever(search_kwargs={"k":10})

In [38]:
query = "what is supervised learining"

In [39]:
results = vdb.similarity_search_with_score(query, k=3)

In [43]:
context = "\n\n".join(
    [doc.page_content for doc, score in results]
)

In [44]:
context

'Examples concerning the sklearn.gaussian_process module. Gaussian process classification (GPC) on iris dataset Gaussian processes on discrete data structures Illustration of Gaussian process classification (GPC) on the XOR dataset Illustration of prior and posterior Gaussian process for different kernels Iso-probability lines for Gaussian Processes classification (GPC) Probabilistic predictions with Gaussian process classification (GPC) Examples concerning the sklearn.linear_model module. Lasso on dense and sparse data Examples related to the sklearn.inspection module. Failure of Machine Learning to infer causal effects Examples concerning the sklearn.kernel_approximation module. Examples concerning the sklearn.manifold module. Comparison of Manifold Learning methods Manifold Learning methods on a severed sphere Swiss Roll And Swiss-Hole Reduction t-SNE: The effect of various perplexity values on the shape Miscellaneous and introductory examples for scikit-learn. Comparing anomaly detection algorithms for outlier detection on toy datasets Developing Estimators Compliant with Metadata Routing Examples concerning the sklearn.impute module. Examples related to the sklearn.model_selection module. Multiclass Receiver Operating Characteristic (ROC) Receiver Operating Characteristic (ROC) with cross validation Examples concerning the sklearn.multiclass module. Examples concerning the sklearn.multioutput module. Multilabel classification using a classifier chain Examples concerning the sklearn.neighbors module. Approximate nearest neighbors in TSNE Kernel Density Estimate of Species Distributions Nearest Centroid Classification Nearest Neighbors regression Novelty detection with Local Outlier Factor (LOF) Outlier detection with Local Outlier Factor (LOF) Simple 1D Kernel Density Estimation Examples concerning the sklearn.neural_network module. Visualization of MLP weights on MNIST Examples of how to compose transformers and pipelines from other estimators. See the User Guide . Examples concerning the sklearn.preprocessing module. Map data to a normal distribution Examples concerning the sklearn.semi_supervised module. Examples concerning the sklearn.svm module. One-class SVM with non-linear kernel (RBF) Plot the support vectors in LinearSVC SVM Margins Example SVM Tie Breaking Example Examples concerning the sklearn.feature_extraction.text module. Download all examples in Python source code: auto_examples_python.zip Download all examples in Jupyter notebooks: auto_examples_jupyter.zip Gallery generated by Sphinx-Gallery Release Highlights sklearn.metrics # Model selection interface # Classification metrics # Regression metrics # Multilabel ranking metrics # Clustering metrics # Biclustering metrics # Distance metrics # Pairwise metrics # Plotting # Score functions, performance metrics, pairwise metrics and distance computations. User guide. See the Metrics and scoring: quantifying the quality of predictions and Pairwise metrics, Affinities and Kernels sections for further details. User guide. See the The scoring parameter: defining model evaluation rules section for further details. User guide. See the Classification metrics section for further details. User guide. See the Regression metrics section for further details. User guide. See the Multilabel ranking metrics section for further details. Evaluation metrics for cluster analysis results. Supervised evaluation uses a ground truth class values for each sample. Unsupervised evaluation does not use ground truths and measures the “quality” of the\nmodel itself. User guide. See the Clustering performance evaluation section for further details. cluster.contingency_matrix cluster.pair_confusion_matrix User guide. See the Biclustering evaluation section for further details. Metrics for pairwise distances and affinity of sets of samples. User guide. See the Pairwise metrics, Affinities and Kernels section for further details. pairwise.additive_chi2_kernel pairwise.chi2_kernel pairwise.cosine_distances pairwise.cosine_similarity pairwise.distance_metrics pairwise.euclidean_distances pairwise.haversine_distances pairwise.kernel_metrics pairwise.laplacian_kernel pairwise.linear_kernel pairwise.manhattan_distances pairwise.nan_euclidean_distances pairwise.paired_cosine_distances pairwise.paired_distances pairwise.paired_euclidean_distances pairwise.paired_manhattan_distances pairwise.pairwise_kernels pairwise.polynomial_kernel pairwise.rbf_kernel pairwise.sigmoid_kernel User guide. See the Visualizations section for further details. NotFittedError # This class inherits from both ValueError and AttributeError to help with\nexception handling and backward compatibility. Changed in version 0.18: Moved from sklearn.utils.validation. >>> from sklearn.svm import LinearSVC >>> from sklearn.exceptions import NotFittedError >>> try : ... LinearSVC () . predict ([[ 1 , 2 ], [ 2 , 3 ], [ 3 , 4 ]]) ... except NotFittedError as e : ... print ( repr ( e )) NotFittedError("This LinearSVC instance is not fitted yet. Call \'fit\' with appropriate arguments before using this estimator."...) check_is_fitted # Checks if the estimator is fitted by verifying the presence of\nfitted attributes (ending with a trailing underscore) and otherwise\nraises a NotFittedError with the given message. If an estimator does not set any attributes with a trailing underscore, it\ncan define a __sklearn_is_fitted__ method returning a boolean to\nspecify if the estimator is fitted or not. See __sklearn_is_fitted__ as Developer API for an example on how to use the API. If no attributes are passed, this function will pass if an estimator is stateless.\nAn estimator can indicate it’s stateless by setting the requires_fit tag. See Estimator Tags for more information. Note that the requires_fit tag\nis ignored if attributes are passed. Estimator instance for which the check is performed. Attribute name(s) given as string or a list/tuple of strings\nEg.: ["coef_", "estimator_", ...], "coef_" If None , estimator is considered fitted if there exist an\nattribute that ends with a underscore and does not start with double\nunderscore. The default error message is, “This %(name)s instance is not fitted\nyet. Call ‘fit’ with appropriate arguments before using this\nestimator.” For custom messages if “%(name)s” is present in the message string,\nit is substituted for the estimator name. Eg. : “Estimator, %(name)s, must be fitted before sparsifying”. Specify whether all or any of the given attributes must exist. If the estimator is a class or not an estimator instance If the attributes are not found. >>> from sklearn.linear_model import LogisticRegression >>> from sklearn.utils.validation import check_is_fitted >>> from sklearn.exceptions import NotFittedError >>> lr = LogisticRegression () >>> try : ... check_is_fitted ( lr ) ... except NotFittedError as exc : ... print ( f "Model is not fitted yet." ) Model is not fitted yet. >>> lr . fit ([[ 1 , 2 ], [ 1 , 3 ]], [ 1 , 0 ]) LogisticRegression() >>> check_is_fitted ( lr ) enet_path # The elastic net optimization function varies for mono and multi-outputs. For mono-output tasks it is: For multi-output tasks it is: Where: i.e. the sum of L2-norm of each row (task) (i=feature, j=task) Training data. Pass directly as Fortran-contiguous data to avoid\nunnecessary memory duplication. If y is mono-output then X can be sparse. Number between 0 and 1 passed to elastic net (scaling between\nl1 and l2 penalties). l1_ratio=1 corresponds to the Lasso. Length of the path. eps=1e-3 means that alpha_min / alpha_max = 1e-3 . Number of alphas along the regularization path. List of alphas where to compute the models.\nIf None alphas are set automatically. Whether to use a precomputed Gram matrix to speed up\ncalculations. If set to \'auto\' let us decide. The Gram\nmatrix can also be passed as argument. Xy = np.dot(X.T, y) that can be precomputed. It is useful\nonly when the Gram matrix is precomputed. If True , X will be copied; else, it may be overwritten. The initial values of the coefficients. Amount of verbosity. Whether to return the number of iterations or not. If set to True, forces coefficients to be positive.\n(Only allowed when y.ndim == 1 ). If set to False, the input validation checks are skipped (including the\nGram matrix when provided). It is assumed that they are handled\nby the caller. Keyword arguments passed to the coordinate descent solver. The alphas along the path where models are computed. Coefficients along the path. The dual gaps at the end of the optimization for each alpha. The number of iterations taken by the coordinate descent optimizer to\nreach the specified tolerance for each alpha.\n(Is returned when return_n_iter is set to True). Multi-task ElasticNet model trained with L1/L2 mixed-norm     as regularizer. For an example, see examples/linear_model/plot_lasso_lasso_lars_elasticnet_path.py . The underlying coordinate descent solver uses gap safe screening rules to speedup\nfitting time, see User Guide on coordinate descent . 1 / ( 2 * n_samples ) * || y - Xw ||^ 2_2 + alpha * l1_ratio * || w || _1 + 0.5 * alpha * ( 1 - l1_ratio ) * || w ||^ 2_2 1 / ( 2 * n_samples ) * || Y - XW || _Fro ^ 2 + alpha * l1_ratio * || W || _21 + 0.5 * alpha * ( 1 - l1_ratio ) * || W || _Fro ^ 2 || W || _21 = \\ sum_i \\ sqrt { \\ sum_j w_ { ij } ^ 2 } >>> from sklearn.linear_model import enet_path >>> from sklearn.datasets import make_regression >>> X , y , true_coef = make_regression ( ... n_samples = 100 , n_features = 5 , n_informative = 2 , coef = True , random_state = 0 ... ) >>> true_coef array([ 0.        ,  0.        ,  0.        , 97.9, 45.7]) >>> alphas , estimated_coef , _ = enet_path ( X , y , alphas = 3 ) >>> alphas . shape (3,) >>> estimated_coef array([[ 0.,  0.787,  0.568], [ 0.,  1.120,  0.620], [-0., -2.129, -1.128], [ 0., 23.046, 88.939], [ 0., 10.637, 41.566]]) spectral_embedding # The adjacency matrix is used to compute a normalized graph Laplacian\nwhose spectrum (especially the eigenvectors associated to the\nsmallest eigenvalues) has an interpretation in terms of minimal\nnumber of cuts necessary to split the graph into comparably sized\ncomponents. This embedding can also ‘work’ even if the adjacency variable is\nnot strictly the adjacency matrix of a graph but more generally\nan affinity or similarity matrix between samples (for instance the\nheat kernel of a euclidean distance matrix or a k-NN matrix). However care must taken to always make the affinity matrix symmetric\nso that the eigenvector decomposition works as expected. Note : Laplacian Eigenmaps is the actual algorithm implemented here. The adjacency matrix of the graph to embed. The dimension of the projection subspace. The eigenvalue decomposition strategy to use. AMG requires pyamg\nto be installed. It can be faster on very large, sparse problems,\nbut may also lead to instabilities. If None, then \'arpack\' is\nused. A pseudo random number generator used for the initialization\nof the lobpcg eigen vectors decomposition when eigen_solver == \'amg\' , and for the K-Means initialization. Use an int to make\nthe results deterministic across calls (See Glossary ). When using eigen_solver == \'amg\' ,\nit is necessary to also fix the global numpy seed with np.random.seed(int) to get deterministic results. See pyamg/pyamg#139 for further\ninformation. Stopping criterion for eigendecomposition of the Laplacian matrix.\nIf eigen_tol="auto" then the passed tolerance will depend on the eigen_solver : If eigen_solver="arpack" , then eigen_tol=0.0 ; If eigen_solver="lobpcg" or eigen_solver="amg" , then eigen_tol=None which configures the underlying lobpcg solver to\nautomatically resolve the value according to their heuristics. See, scipy.sparse.linalg.lobpcg for details. Note that when using eigen_solver="amg" values of tol<1e-5 may lead\nto convergence issues and should be avoided. Added in version 1.2: Added ‘auto’ option. If True, then compute symmetric normalized Laplacian. Whether to drop the first eigenvector. For spectral embedding, this\nshould be True as the first eigenvector should be constant vector for\nconnected graph, but for spectral clustering, this should be kept as\nFalse to retain the first eigenvector. The reduced samples. Spectral Embedding (Laplacian Eigenmaps) is most useful when the graph\nhas one connected component. If there graph has many components, the first\nfew eigenvectors will simply uncover the connected components of the graph. https://en.wikipedia.org/wiki/LOBPCG “Toward the Optimal Preconditioned Eigensolver: Locally Optimal\nBlock Preconditioned Conjugate Gradient Method”,\nAndrew V. Knyazev >>> from sklearn.datasets import load_digits >>> from sklearn.neighbors import kneighbors_graph >>> from sklearn.manifold import spectral_embedding >>> X , _ = load_digits ( return_X_y = True ) >>> X = X [: 100 ] >>> affinity_matrix = kneighbors_graph ( ... X , n_neighbors = int ( X . shape [ 0 ] / 10 ), include_self = True ... ) >>> # make the matrix symmetric >>> affinity_matrix = 0.5 * ( affinity_matrix + affinity_matrix . T ) >>> embedding = spectral_embedding ( affinity_matrix , n_components = 2 , random_state = 42 ) >>> embedding . shape (100, 2) dbscan # This function is a wrapper around DBSCAN , suitable for\nquick, standalone clustering tasks. For estimator-based workflows, where\nestimator attributes or pipeline integration is required, prefer DBSCAN . DBSCAN (Density-Based Spatial Clustering of Applications with Noise) is a\ndensity-based clustering algorithm that groups together points that are\nclosely packed while marking points in low-density regions as outliers. A feature array, or array of distances between samples if metric=\'precomputed\' . When using precomputed distances, X must\nbe a square symmetric matrix. The maximum distance between two samples for one to be considered\nas in the neighborhood of the other. This is not a maximum bound\non the distances of points within a cluster. This is the most\nimportant DBSCAN parameter to choose appropriately for your data set\nand distance function. Smaller values result in more clusters,\nwhile larger values result in fewer, larger clusters. The number of samples (or total weight) in a neighborhood for a point\nto be considered as a core point. This includes the point itself.\nHigher values yield fewer, denser clusters, while lower values yield\nmore, sparser clusters. The metric to use when calculating distance between instances in a\nfeature array. If metric is a string or callable, it must be one of\nthe options allowed by sklearn.metrics.pairwise_distances for\nits metric parameter.\nIf metric is “precomputed”, X is assumed to be a distance matrix and\nmust be square during fit.\nX may be a sparse graph ,\nin which case only “nonzero” elements may be considered neighbors. Additional keyword arguments for the metric function. The algorithm to be used by the NearestNeighbors module\nto compute pointwise distances and find nearest neighbors.\n‘auto’ will attempt to decide the most appropriate algorithm\nbased on the values passed to fit method.\nSee NearestNeighbors documentation for\ndetails. Leaf size passed to BallTree or cKDTree. This can affect the speed\nof the construction and query, as well as the memory required\nto store the tree. The optimal value depends\non the nature of the problem. Generally, smaller leaf sizes\nlead to faster queries but slower construction. Power parameter for the Minkowski metric. When p = 1, this is equivalent\nto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.\nFor arbitrary p, minkowski_distance (l_p) is used. This parameter is expected\nto be positive. Weight of each sample, such that a sample with a weight of at least min_samples is by itself a core sample; a sample with negative\nweight may inhibit its eps-neighbor from being core.\nNote that weights are absolute, and default to 1. The number of parallel jobs to run for neighbors search. None means\n1 unless in a joblib.parallel_backend context. -1 means\nusing all processors. See Glossary for more details.\nIf precomputed distances are used, parallel execution is not available\nand thus n_jobs will have no effect. Indices of core samples. Cluster labels for each point. Noisy samples are given the label -1.\nNon-negative integers indicate cluster membership. An estimator interface for this clustering algorithm. A similar estimator interface clustering at multiple values of eps. Our implementation is optimized for memory usage. For an example, see Demo of DBSCAN clustering algorithm . This implementation bulk-computes all neighborhood queries, which increases\nthe memory complexity to O(n.d) where d is the average number of neighbors,\nwhile original DBSCAN had memory complexity O(n). It may attract a higher\nmemory complexity when querying these nearest neighborhoods, depending\non the algorithm . One way to avoid the query complexity is to pre-compute sparse\nneighborhoods in chunks using NearestNeighbors.radius_neighbors_graph with mode=\'distance\' , then using metric=\'precomputed\' here. Another way to reduce memory and computation time is to remove\n(near-)duplicate points and use sample_weight instead. OPTICS provides a similar clustering with lower\nmemory usage. Ester, M., H. P. Kriegel, J. Sander, and X. Xu, “A Density-Based\nAlgorithm for Discovering Clusters in Large Spatial Databases with Noise” .\nIn: Proceedings of the 2nd International Conference on Knowledge Discovery\nand Data Mining, Portland, OR, AAAI Press, pp. 226-231. 1996 Schubert, E., Sander, J., Ester, M., Kriegel, H. P., & Xu, X. (2017). “DBSCAN revisited, revisited: why and how you should (still) use DBSCAN.” ACM Transactions on Database Systems (TODS), 42(3), 19. >>> from sklearn.cluster import dbscan >>> X = [[ 1 , 2 ], [ 2 , 2 ], [ 2 , 3 ], [ 8 , 7 ], [ 8 , 8 ], [ 25 , 80 ]] >>> core_samples , labels = dbscan ( X , eps = 3 , min_samples = 2 ) >>> core_samples array([0, 1, 2, 3, 4]) >>> labels array([ 0,  0,  0,  1,  1, -1]) maxabs_scale # This estimator scales each feature individually such\nthat the maximal absolute value of each feature in the\ntraining set will be 1.0. This scaler can also be applied to sparse CSR or CSC matrices. Axis used to scale along. If 0, independently scale each feature,\notherwise (if 1) scale each sample. If False, try to avoid a copy and scale in place.\nThis is not guaranteed to always work in place; e.g. if the data is\na numpy array with an int dtype, a copy will be returned even with\ncopy=False. Risk of data leak\nDo not use maxabs_scale unless you know\nwhat you are doing. A common mistake is to apply it to the entire data before splitting into training and test sets. This will bias the\nmodel evaluation because information would have leaked from the test\nset to the training set.\nIn general, we recommend using MaxAbsScaler within a Pipeline in order to prevent most risks of data\nleaking: pipe = make_pipeline(MaxAbsScaler(), LogisticRegression()) . Performs scaling to the [-1, 1] range using the Transformer API (e.g. as part of a preprocessing Pipeline ). NaNs are treated as missing values: disregarded to compute the statistics,\nand maintained during the data transformation. For a comparison of the different scalers, transformers, and normalizers,\nsee: Compare the effect of different scalers on data with outliers . >>> from sklearn.preprocessing import maxabs_scale >>> X = [[ - 2 , 1 , 2 ], [ - 1 , 0 , 1 ]] >>> maxabs_scale ( X , axis = 0 ) # scale each column independently array([[-1. ,  1. ,  1. ], [-0.5,  0. ,  0.5]]) >>> maxabs_scale ( X , axis = 1 ) # scale each row independently array([[-1. ,  0.5,  1. ], [-1. ,  0. ,  1. ]]) sklearn.pipeline # Utilities to build a composite estimator as a chain of transforms and estimators. User guide. See the Pipelines and composite estimators section for further details. sklearn.model_selection # Splitters # Hyper-parameter optimizers # Post-fit 

In [45]:
prompt = f"""
You are a Retrieval-Augmented Generation (RAG) assistant.

Answer ONLY using the context below.

If the answer cannot be found in the context,
reply exactly:

"I cannot find the answer in the provided context."

Context:
{context}

Question:
{query}

Answer:
"""

In [ ]:
import google.generativeai as genai

genai.configure(api_key="private")

model = genai.GenerativeModel("gemini-2.5-flash")

response = model.generate_content(prompt)

print(response.text)

I cannot find the answer in the provided context.